name: Exploring Variables and Secrets

on:
    push

env: 
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: yzhangtufts
  IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: yzhangtufts
                IMAGE_NAME: github-actions-nginx
              run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
            
            - name: Docker login
              env:
                DOCKER_PASSWORD: s3cUrePaSswOrd
                DOCKER_USERNAME: yzhangtufts
              run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

            - name: Docker Publish
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: yzhangtufts
                IMAGE_NAME: github-actions-nginx
              run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest